import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#1677EF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirectoryServiceConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('directory_type', models.CharField(choices=[('active_directory', 'Microsoft Active Directory'), ('generic_ldap', 'Generic LDAP')], default='generic_ldap', max_length=30)),
                ('primary_host', models.CharField(blank=True, default='', max_length=255)),
                ('primary_port', models.PositiveIntegerField(blank=True, null=True)),
                ('secondary_host', models.CharField(blank=True, default='', max_length=255)),
                ('secondary_port', models.PositiveIntegerField(blank=True, null=True)),
                ('base_dn', models.CharField(blank=True, default='', max_length=255)),
                ('bind_dn', models.CharField(blank=True, default='', max_length=255)),
                ('bind_password_encrypted', models.TextField(blank=True, default='')),
                ('security_mode', models.CharField(choices=[('ldaps', 'LDAPS'), ('starttls', 'StartTLS'), ('none', 'None')], default='ldaps', max_length=20)),
                ('tls_server_name', models.CharField(blank=True, default='', max_length=255)),
                ('ca_cert_file', models.CharField(blank=True, default='', max_length=500)),
                ('user_search_base', models.CharField(blank=True, default='', max_length=255)),
                ('user_login_attribute', models.CharField(default='uid', max_length=80)),
                ('user_filter', models.CharField(default='(&(objectClass=inetOrgPerson)(uid={username}))', max_length=500)),
                ('external_id_attribute', models.CharField(default='entryUUID', max_length=80)),
                ('email_attribute', models.CharField(default='mail', max_length=80)),
                ('first_name_attribute', models.CharField(default='givenName', max_length=80)),
                ('last_name_attribute', models.CharField(default='sn', max_length=80)),
                ('account_control_attribute', models.CharField(blank=True, default='', max_length=80)),
                ('connect_timeout', models.PositiveIntegerField(default=5)),
                ('operation_timeout', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('rack_type', models.CharField(blank=True, default='标准机柜', max_length=80)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('total_u', models.PositiveSmallIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('in_use', '使用中'), ('reserved', '预留'), ('disabled', '停用')], default='in_use', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('default_page_size', models.PositiveSmallIntegerField(choices=[(20, '20'), (50, '50'), (100, '100')], default=50)),
                ('default_asset_status', models.CharField(choices=[('in_stock', '在库'), ('in_use', '在用'), ('idle', '闲置'), ('retired', '已报废')], default='in_stock', max_length=20)),
                ('default_locale', models.CharField(choices=[('zh-CN', '简体中文'), ('en-US', 'English')], default='zh-CN', max_length=10)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY')], default='YYYY-MM-DD', max_length=20)),
                ('currency', models.CharField(choices=[('CNY', 'CNY (¥)'), ('USD', 'USD ($)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)'), ('HKD', 'HKD (HK$)')], default='CNY', max_length=3)),
                ('password_min_length', models.PositiveSmallIntegerField(default=8)),
                ('password_expiry_days', models.PositiveIntegerField(default=0)),
                ('login_max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('login_window_seconds', models.PositiveIntegerField(default=900)),
                ('login_lock_seconds', models.PositiveIntegerField(default=900)),
                ('smtp_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security_mode', models.CharField(choices=[('none', 'None'), ('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=10)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, default='')),
                ('smtp_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('smtp_from_name', models.CharField(blank=True, default='', max_length=150)),
                ('smtp_timeout', models.PositiveSmallIntegerField(default=10)),
                ('notify_maintenance', models.BooleanField(default=True)),
                ('maintenance_expiry_days', models.PositiveSmallIntegerField(default=30)),
                ('notify_license_expiry', models.BooleanField(default=True)),
                ('license_expiry_days', models.PositiveSmallIntegerField(default=30)),
                ('notify_open_faults', models.BooleanField(default=True)),
                ('notify_overdue_inventory', models.BooleanField(default=True)),
                ('notify_low_spare_stock', models.BooleanField(default=True)),
                ('branding_display_name', models.CharField(default='infrix', max_length=80)),
                ('branding_logo', models.BinaryField(blank=True, default=bytes)),
                ('branding_compact_logo', models.BinaryField(blank=True, default=bytes)),
                ('branding_favicon', models.BinaryField(blank=True, default=bytes)),
                ('email_digest_enabled', models.BooleanField(default=False)),
                ('email_digest_recipients', models.JSONField(blank=True, default=list)),
                ('application_url', models.URLField(blank=True, default='', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=80)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthThrottleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('account', '账号'), ('ip', 'IP')], max_length=16)),
                ('key', models.CharField(max_length=255)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('first_failed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'key'), name='uniq_auth_throttle_scope_key')],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('date', '日期'), ('select', '下拉单选'), ('multiselect', '多选'), ('boolean', '是/否')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.CharField(blank=True, default='', max_length=80)),
                ('help_text', models.TextField(blank=True, default='', max_length=1000)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('form_visible', models.BooleanField(default=True)),
                ('detail_visible', models.BooleanField(default=True)),
                ('list_visible', models.BooleanField(default=False)),
                ('filterable', models.BooleanField(default=False)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='assets.devicetype')),
            ],
            options={
                'ordering': ['device_type__name', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=160)),
                ('employee_no', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('contact', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='assets.department')),
            ],
            options={
                'ordering': ['name', 'employee_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_no', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('manufacturer_model', models.CharField(blank=True, max_length=160)),
                ('serial_number', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('in_stock', '在库'), ('in_use', '在用'), ('idle', '闲置'), ('repair', '维修中'), ('retired', '已报废')], default='in_stock', max_length=20)),
                ('status_before_repair', models.CharField(blank=True, choices=[('in_stock', '在库'), ('in_use', '在用'), ('idle', '闲置'), ('repair', '维修中'), ('retired', '已报废')], default=None, editable=False, help_text='由故障维修生命周期维护的维修前资产状态快照', max_length=20, null=True)),
                ('depreciation_start_date', models.DateField(blank=True, null=True)),
                ('depreciation_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residual_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('depreciation_method', models.CharField(blank=True, choices=[('straight_line', '直线法')], default=None, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('asset_data_center', models.ForeignKey(blank=True, help_text='未上架资产的所属数据中心；已上架资产以机柜归属为准', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unmounted_assets', to='assets.datacenter')),
                ('assigned_person', models.ForeignKey(blank=True, help_text='当前使用人；指定、归还和转交通过使用人操作维护', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assets', to='assets.person')),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.devicetype')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaultEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fault_events', to='assets.asset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_date', models.DateField()),
                ('recipient_key', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('recipient_count', models.PositiveSmallIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('window_date', 'recipient_key'), name='unique_digest_recipient_day')],
            },
        ),
        migrations.CreateModel(
            name='RackUnitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_u', models.PositiveSmallIntegerField()),
                ('end_u', models.PositiveSmallIntegerField()),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rack_allocation', to='assets.asset')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='assets.rack')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('fault', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='assets.faultevent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='assets.datacenter')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racks', to='assets.serverroom'),
        ),
        migrations.CreateModel(
            name='InventoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成')], default='in_progress', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='assets.datacenter')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to=settings.AUTH_USER_MODEL)),
                ('server_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_tasks', to='assets.serverroom')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('license_type', models.CharField(blank=True, max_length=80)),
                ('authorized_count', models.PositiveIntegerField(default=0)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_licenses', to='assets.manufacturer')),
            ],
            options={
                'ordering': ['expiry_date', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('model', models.CharField(blank=True, max_length=160)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(choices=[('piece', '个'), ('block', '块'), ('stick', '条'), ('root', '根'), ('set', '套'), ('pair', '对'), ('box', '盒')], default='piece', max_length=20)),
                ('safety_stock', models.PositiveIntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='assets.manufacturer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='assets.sparepartcategory')),
            ],
            options={
                'ordering': ['name', 'category__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SpareStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('normalized_server_room_id', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('server_room_id', models.Value(0), output_field=models.BigIntegerField()), output_field=models.BigIntegerField())),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spare_stocks', to='assets.datacenter')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='assets.sparepart')),
                ('server_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_stocks', to='assets.serverroom')),
            ],
            options={
                'ordering': ['part__name', 'data_center__name', 'server_room__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RepairPartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('internal_stock', '内部库存'), ('vendor_provided', '厂商提供')], max_length=30)),
                ('part_code', models.CharField(blank=True, max_length=80)),
                ('part_name', models.CharField(max_length=160)),
                ('part_model', models.CharField(blank=True, max_length=160)),
                ('part_unit', models.CharField(blank=True, max_length=20)),
                ('vendor_name', models.CharField(blank=True, max_length=160)),
                ('stock_data_center_name', models.CharField(blank=True, max_length=120)),
                ('stock_server_room_name', models.CharField(blank=True, max_length=120)),
                ('quantity', models.PositiveIntegerField()),
                ('operator_name', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_usages', to='assets.faultevent')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_part_usages', to=settings.AUTH_USER_MODEL)),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_part_usages', to='assets.sparepart')),
                ('spare_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_part_usages', to='assets.sparestock')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SpareStockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('initial', '初始库存'), ('inbound', '入库'), ('outbound', '出库'), ('transfer', '调拨'), ('adjustment', '调整'), ('scrap', '报废')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_delta', models.IntegerField()),
                ('before_quantity', models.PositiveIntegerField(default=0)),
                ('after_quantity', models.PositiveIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='assets.sparepart')),
                ('source_data_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_source_transactions', to='assets.datacenter')),
                ('source_server_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_source_transactions', to='assets.serverroom')),
                ('target_data_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_target_transactions', to='assets.datacenter')),
                ('target_server_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spare_target_transactions', to='assets.serverroom')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_tags', to='assets.asset')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_tags', to='assets.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(choices=[('zh-CN', '简体中文'), ('en-US', 'English')], default='zh-CN', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssetNetworkAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField()),
                ('role', models.CharField(choices=[('business', '业务 IP'), ('management', '管理 IP'), ('oob', '带外 IP')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_addresses', to='assets.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('address',), name='uniq_network_address'), models.UniqueConstraint(fields=('asset', 'role'), name='uniq_asset_network_role')],
            },
        ),
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(max_length=60)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='assets.asset')),
                ('target_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='assets.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_asset', 'target_asset', 'relation_type'), name='uniq_asset_relation'), models.CheckConstraint(condition=models.Q(('source_asset', models.F('target_asset')), _negated=True), name='asset_relation_not_self')],
            },
        ),
        migrations.CreateModel(
            name='AssetAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', '领用'), ('return', '归还'), ('transfer', '调拨')], max_length=20)),
                ('from_person_employee_no', models.CharField(blank=True, max_length=80)),
                ('from_person_name', models.CharField(blank=True, max_length=160)),
                ('from_person_department', models.CharField(blank=True, max_length=120)),
                ('from_person_organization', models.CharField(blank=True, max_length=160)),
                ('from_person_contact', models.CharField(blank=True, max_length=160)),
                ('to_person_employee_no', models.CharField(blank=True, max_length=80)),
                ('to_person_name', models.CharField(blank=True, max_length=160)),
                ('to_person_department', models.CharField(blank=True, max_length=120)),
                ('to_person_organization', models.CharField(blank=True, max_length=160)),
                ('to_person_contact', models.CharField(blank=True, max_length=160)),
                ('operator_name', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='assets.asset')),
                ('from_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_from_events', to='assets.person')),
                ('to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_to_events', to='assets.person')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_assignment_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['asset', '-created_at', '-id'], name='assets_asse_asset_i_d7247e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetCustomValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='assets.asset')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_values', to='assets.customfield')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'field'), name='uniq_asset_custom_value'), models.CheckConstraint(condition=models.Q(models.Q(('text_value', ''), ('number_value__isnull', True), _connector='OR'), models.Q(('text_value', ''), ('date_value__isnull', True), _connector='OR'), models.Q(('text_value', ''), ('boolean_value__isnull', True), _connector='OR'), models.Q(('text_value', ''), ('json_value__isnull', True), _connector='OR'), models.Q(('number_value__isnull', True), ('date_value__isnull', True), _connector='OR'), models.Q(('number_value__isnull', True), ('boolean_value__isnull', True), _connector='OR'), models.Q(('number_value__isnull', True), ('json_value__isnull', True), _connector='OR'), models.Q(('date_value__isnull', True), ('boolean_value__isnull', True), _connector='OR'), models.Q(('date_value__isnull', True), ('json_value__isnull', True), _connector='OR'), models.Q(('boolean_value__isnull', True), ('json_value__isnull', True), _connector='OR')), name='asset_custom_value_one_storage')],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assets.customfield')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('field', 'value'), name='uniq_custom_field_option_value')],
            },
        ),
        migrations.CreateModel(
            name='DirectoryIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='ldap', max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('current_login_identifier', models.CharField(max_length=150)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='directory_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='uniq_directory_identity_provider_external_id')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(blank=True, max_length=160)),
                ('contract_no', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_contracts', to='assets.asset')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('asset',), name='uniq_current_maintenance_per_asset')],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=160)),
                ('order_no', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_records', to='assets.asset')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('asset',), name='uniq_current_procurement_per_asset')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '未盘点'), ('normal', '正常'), ('location_mismatch', '位置不符'), ('not_found', '未找到'), ('info_mismatch', '设备信息不符'), ('other', '其他异常')], default='pending', max_length=30)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('actual_start_u', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_end_u', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolution_status', models.CharField(choices=[('not_required', '无需处理'), ('pending', '待处理'), ('resolved', '已处理')], default='not_required', max_length=20)),
                ('resolution_action', models.CharField(blank=True, choices=[('update_asset', '更新资产台账'), ('keep_asset', '保持资产台账'), ('confirm_missing', '确认设备缺失'), ('ignore', '忽略/误报')], max_length=30, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='assets.asset')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_inventory_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.inventorytask')),
                ('actual_rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='assets.rack')),
            ],
            options={
                'ordering': ['asset__asset_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('task', 'asset'), name='uniq_inventory_item_task_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='serverroom',
            constraint=models.UniqueConstraint(fields=('data_center', 'name'), name='uniq_room_per_dc'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('room', 'code'), name='uniq_rack_per_room'),
        ),
        migrations.AddConstraint(
            model_name='softwarelicense',
            constraint=models.CheckConstraint(condition=models.Q(('used_count__lte', models.F('authorized_count'))), name='license_used_lte_authorized'),
        ),
        migrations.AddConstraint(
            model_name='sparestock',
            constraint=models.UniqueConstraint(fields=('part', 'data_center', 'normalized_server_room_id'), name='uniq_spare_stock_location_key'),
        ),
        migrations.AddConstraint(
            model_name='sparestock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='spare_stock_quantity_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='repairpartusage',
            index=models.Index(fields=['fault', '-created_at', '-id'], name='assets_repa_fault_i_c75e0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='repairpartusage',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='repair_part_usage_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='repairpartusage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source', 'internal_stock'), ('spare_part__isnull', False), ('spare_stock__isnull', False), ('vendor_name', '')), models.Q(('source', 'vendor_provided'), ('spare_stock__isnull', True)), _connector='OR'), name='repair_part_usage_source_consistent'),
        ),
        migrations.AddConstraint(
            model_name='assettag',
            constraint=models.UniqueConstraint(fields=('asset', 'tag'), name='uniq_asset_tag'),
        ),
    ]
