# Generated by Django 5.2.17 on 2026-09-01 09:55

import django.db.models.functions.comparison
from django.db.models import Count
from django.db import migrations, models


def fail_if_spare_stock_locations_are_already_duplicated(apps, schema_editor):
    SpareStock = apps.get_model("assets", "SpareStock")
    duplicates = list(
        SpareStock.objects.values("part_id", "data_center_id", "server_room_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)[:10]
    )
    if duplicates:
        raise RuntimeError(
            "Cannot add the SpareStock location uniqueness constraint because "
            f"duplicate logical locations already exist: {duplicates}. "
            "Clean these rows before retrying the migration; no stock data was changed."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            fail_if_spare_stock_locations_are_already_duplicated,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='sparestock',
            name='normalized_server_room_id',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce('server_room_id', models.Value(0), output_field=models.BigIntegerField()), output_field=models.BigIntegerField()),
        ),
        migrations.AddConstraint(
            model_name='sparestock',
            constraint=models.UniqueConstraint(fields=('part', 'data_center', 'normalized_server_room_id'), name='uniq_spare_stock_location_key'),
        ),
        migrations.RemoveConstraint(
            model_name='sparestock',
            name='uniq_spare_stock_location',
        ),
    ]
