# Generated by Django 5.2.17 on 2026-09-23 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='default_asset_status',
            field=models.CharField(choices=[('in_stock', '在库'), ('in_use', '在用'), ('idle', '闲置')], default='in_stock', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposed_on', models.DateField()),
                ('reason', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disposal', to='assets.asset')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['disposed_on', '-created_at', '-id'], name='assets_disposal_date_idx')],
            },
        ),
    ]
