# Generated by Django 5.2.17 on 2026-08-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetrelation',
            constraint=models.CheckConstraint(condition=models.Q(('source_asset', models.F('target_asset')), _negated=True), name='asset_relation_not_self'),
        ),
    ]
