# Generated by Django 5.2.17 on 2026-09-02 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetcustomvalue_storage_invariant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='responsible_user',
            field=models.ForeignKey(blank=True, help_text='当前正式责任人；领用、归还和调拨通过资产责任动作维护', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssetResponsibilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('assign', '领用'), ('return', '归还'), ('transfer', '调拨')], max_length=20)),
                ('from_user_name', models.CharField(blank=True, max_length=150)),
                ('to_user_name', models.CharField(blank=True, max_length=150)),
                ('operator_name', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsibility_events', to='assets.asset')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_responsibility_from_events', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_responsibility_events', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_responsibility_to_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['asset', '-created_at', '-id'], name='assets_asse_asset_i_6234be_idx')],
            },
        ),
    ]
