# Generated by Django 5.2.17 on 2026-09-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_responsible_user_assetresponsibilityevent'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auththrottlestate',
            name='assets_auth_scope_9fd68f_idx',
        ),
    ]
