# Generated by Django 5.2.17 on 2026-09-03

from ipaddress import ip_address

from django.db import migrations, models


def canonicalize_network_addresses(apps, schema_editor):
    AssetNetworkAddress = apps.get_model("assets", "AssetNetworkAddress")
    db_alias = schema_editor.connection.alias
    seen = {}
    for row in AssetNetworkAddress.objects.using(db_alias).order_by("id").iterator():
        raw_address = str(row.address or "").strip()
        try:
            canonical = ip_address(raw_address).compressed
        except ValueError as exc:
            raise RuntimeError(
                f"AssetNetworkAddress {row.pk} contains an invalid IP address; "
                "clean the data before applying the network integrity migration."
            ) from exc
        previous_id = seen.get(canonical)
        if previous_id is not None:
            raise RuntimeError(
                f"AssetNetworkAddress rows {previous_id} and {row.pk} contain the "
                f"same canonical IP address {canonical}; resolve the duplicate "
                "before applying the network integrity migration."
            )
        seen[canonical] = row.pk
        if row.address != canonical:
            AssetNetworkAddress.objects.using(db_alias).filter(pk=row.pk).update(
                address=canonical,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_repair_part_usage_vendor_snapshot"),
    ]

    operations = [
        migrations.RunPython(
            canonicalize_network_addresses,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="assetnetworkaddress",
            name="uniq_address_role",
        ),
        migrations.AddConstraint(
            model_name="assetnetworkaddress",
            constraint=models.UniqueConstraint(
                fields=("address",),
                name="uniq_network_address",
            ),
        ),
    ]
