# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0009_directory_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectoryServiceConfiguration",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "directory_type",
                    models.CharField(
                        choices=[
                            ("active_directory", "Microsoft Active Directory"),
                            ("generic_ldap", "Generic LDAP"),
                        ],
                        default="generic_ldap",
                        max_length=30,
                    ),
                ),
                ("primary_host", models.CharField(blank=True, default="", max_length=255)),
                ("primary_port", models.PositiveIntegerField(blank=True, null=True)),
                ("secondary_host", models.CharField(blank=True, default="", max_length=255)),
                ("secondary_port", models.PositiveIntegerField(blank=True, null=True)),
                ("base_dn", models.CharField(blank=True, default="", max_length=255)),
                ("bind_dn", models.CharField(blank=True, default="", max_length=255)),
                ("bind_password_encrypted", models.TextField(blank=True, default="")),
                (
                    "security_mode",
                    models.CharField(
                        choices=[
                            ("ldaps", "LDAPS"),
                            ("starttls", "StartTLS"),
                            ("none", "None"),
                        ],
                        default="ldaps",
                        max_length=20,
                    ),
                ),
                ("tls_server_name", models.CharField(blank=True, default="", max_length=255)),
                ("ca_cert_file", models.CharField(blank=True, default="", max_length=500)),
                ("user_search_base", models.CharField(blank=True, default="", max_length=255)),
                ("user_login_attribute", models.CharField(default="uid", max_length=80)),
                (
                    "user_filter",
                    models.CharField(
                        default="(&(objectClass=inetOrgPerson)(uid={username}))",
                        max_length=500,
                    ),
                ),
                ("external_id_attribute", models.CharField(default="entryUUID", max_length=80)),
                ("email_attribute", models.CharField(default="mail", max_length=80)),
                ("first_name_attribute", models.CharField(default="givenName", max_length=80)),
                ("last_name_attribute", models.CharField(default="sn", max_length=80)),
                ("account_control_attribute", models.CharField(blank=True, default="", max_length=80)),
                ("connect_timeout", models.PositiveIntegerField(default=5)),
                ("operation_timeout", models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
