# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0010_directory_service_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="default_locale",
            field=models.CharField(
                choices=[("zh-CN", "简体中文"), ("en-US", "English")],
                default="zh-CN",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="timezone",
            field=models.CharField(default="Asia/Shanghai", max_length=64),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("YYYY-MM-DD", "YYYY-MM-DD"),
                    ("DD/MM/YYYY", "DD/MM/YYYY"),
                    ("MM/DD/YYYY", "MM/DD/YYYY"),
                ],
                default="YYYY-MM-DD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="currency",
            field=models.CharField(
                choices=[
                    ("CNY", "CNY (¥)"),
                    ("USD", "USD ($)"),
                    ("EUR", "EUR (€)"),
                    ("GBP", "GBP (£)"),
                    ("JPY", "JPY (¥)"),
                    ("HKD", "HKD (HK$)"),
                ],
                default="CNY",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="password_min_length",
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="password_expiry_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="login_max_attempts",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="login_window_seconds",
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="login_lock_seconds",
            field=models.PositiveIntegerField(default=900),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_security_mode",
            field=models.CharField(
                choices=[("none", "None"), ("starttls", "STARTTLS"), ("ssl", "SSL/TLS")],
                default="starttls",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_username",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_password_encrypted",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_from_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_from_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="smtp_timeout",
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="notify_maintenance",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="maintenance_expiry_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="notify_license_expiry",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="license_expiry_days",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="notify_open_faults",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="notify_overdue_inventory",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="systemsetting",
            name="notify_low_spare_stock",
            field=models.BooleanField(default=True),
        ),
    ]
