# Generated by Django 5.2.17 on 2026-08-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_inventory_center"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("part_type", models.CharField(choices=[("hard_disk", "备用硬盘"), ("memory", "内存"), ("power_module", "电源模块"), ("optical_module", "光模块"), ("network_card", "网卡"), ("hba_card", "HBA 卡"), ("fan", "风扇"), ("raid_card", "RAID 卡"), ("other", "其他")], default="other", max_length=30)),
                ("model", models.CharField(blank=True, max_length=160)),
                ("specification", models.CharField(blank=True, max_length=255)),
                ("unit", models.CharField(default="件", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("brand", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spare_parts", to="assets.brand")),
            ],
            options={"ordering": ["name", "part_type", "id"]},
        ),
        migrations.CreateModel(
            name="SpareStockTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_type", models.CharField(choices=[("inbound", "入库"), ("outbound", "出库"), ("transfer", "调拨"), ("adjustment", "盘点调整"), ("scrap", "报废")], max_length=20)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("before_quantity", models.PositiveIntegerField(default=0)),
                ("after_quantity", models.PositiveIntegerField(default=0)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("operator", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="spare_stock_transactions", to=settings.AUTH_USER_MODEL)),
                ("part", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transactions", to="assets.sparepart")),
                ("source_data_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="spare_source_transactions", to="assets.datacenter")),
                ("source_server_room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="spare_source_transactions", to="assets.serverroom")),
                ("target_data_center", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="spare_target_transactions", to="assets.datacenter")),
                ("target_server_room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="spare_target_transactions", to="assets.serverroom")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.CreateModel(
            name="SpareStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("data_center", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="spare_stocks", to="assets.datacenter")),
                ("part", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stocks", to="assets.sparepart")),
                ("server_room", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="spare_stocks", to="assets.serverroom")),
            ],
            options={
                "ordering": ["part__name", "data_center__name", "server_room__name", "id"],
                "constraints": [models.UniqueConstraint(fields=("part", "data_center", "server_room"), name="uniq_spare_stock_location")],
            },
        ),
    ]
