# Generated by Django 5.2.17 on 2026-09-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_seed_system_settings_runtime_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='branding_compact_logo',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='branding_display_name',
            field=models.CharField(default='infrix', max_length=80),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='branding_favicon',
            field=models.BinaryField(blank=True, default=bytes),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='branding_logo',
            field=models.BinaryField(blank=True, default=bytes),
        ),
    ]
