# Generated by Django 5.2.17 on 2026-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_system_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='application_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_digest_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_digest_recipients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('window_date', models.DateField()),
                ('recipient_key', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('recipient_count', models.PositiveSmallIntegerField(default=1)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('window_date', 'recipient_key'), name='unique_digest_recipient_day')],
            },
        ),
    ]
