# Generated by Django 5.2.17 on 2026-08-21 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_sparestock_quantity_nonnegative'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='detail_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='form_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='group',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='customfield',
            name='help_text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='customfield',
            name='list_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customfield',
            name='validation_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='assets.devicetype'),
        ),
    ]
