# Generated by Django 5.2.17 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0021_asset_status_before_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="depreciation_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="depreciation_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="residual_rate",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="depreciation_method",
            field=models.CharField(
                blank=True,
                choices=[("straight_line", "直线法")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
