# Generated by Django 5.2.17 on 2026-08-24 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_brand_to_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwarelicense',
            name='vendor',
        ),
        migrations.AddField(
            model_name='softwarelicense',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='software_licenses', to='assets.manufacturer'),
        ),
    ]
