import type { SystemSettingDefinition } from "./types";

const options = (values: Array<string | number>, labels = values.map(String)) =>
  values.map((value, index) => ({ value, label: labels[index] }));

/**
 * Presentation metadata for the system-settings form.
 *
 * This is intentionally local to the frontend.  The API's transition-only
 * `definitions` field is not a source of labels, help text, or choices.
 */
export const SYSTEM_SETTING_DEFINITIONS: SystemSettingDefinition[] = [
  {
    key: "default_page_size",
    label: "默认每页条数",
    type: "integer",
    section: "general",
    default: 50,
    options: options([20, 50, 100]),
    help_text: "作为未指定分页大小的列表默认值；用户已选择的页面大小不受影响。",
  },
  {
    key: "default_asset_status",
    label: "新资产默认状态",
    type: "enum",
    section: "general",
    default: "in_stock",
    options: options(["in_stock", "in_use", "idle", "repair", "retired"], ["在库", "在用", "闲置", "维修中", "已报废"]),
    help_text: "仅影响以后新建或导入且未填写状态的资产，不修改历史资产。",
  },
  {
    key: "default_locale",
    label: "默认界面语言",
    type: "enum",
    section: "general",
    default: "zh-CN",
    options: options(["zh-CN", "en-US"]),
    help_text: "新用户和未设置个人语言偏好的会话使用此语言；用户个人设置优先。",
  },
  {
    key: "date_format",
    label: "日期格式",
    type: "enum",
    section: "general",
    default: "YYYY-MM-DD",
    options: options(["YYYY-MM-DD", "DD/MM/YYYY", "MM/DD/YYYY"]),
    help_text: "影响日期和日期时间在界面中的展示格式。",
  },
  {
    key: "currency",
    label: "默认币种",
    type: "enum",
    section: "general",
    default: "CNY",
    options: options(["CNY", "USD", "EUR", "GBP", "JPY", "HKD"]),
    help_text: "影响金额输入和资产折旧金额的货币符号展示，不会换算已保存金额。",
  },
  {
    key: "password_min_length",
    label: "本地账号密码最小长度",
    type: "integer",
    section: "security",
    default: 8,
    options: [],
    help_text: "只约束本地账号；LDAP / AD 账号仍由目录服务的密码策略约束。",
  },
  {
    key: "password_expiry_days",
    label: "本地账号密码有效期（天）",
    type: "integer",
    section: "security",
    default: 0,
    options: [],
    help_text: "设置为 0 表示不强制过期；过期后本地账号需先修改密码。",
  },
  {
    key: "login_max_attempts",
    label: "登录失败次数上限",
    type: "integer",
    section: "security",
    default: 5,
    options: [],
    help_text: "账号和来源 IP 在窗口内达到上限后会暂时锁定。",
  },
  {
    key: "login_window_seconds",
    label: "失败计数窗口（秒）",
    type: "integer",
    section: "security",
    default: 900,
    options: [],
    help_text: "登录失败次数在此时间窗口内累计。",
  },
  {
    key: "login_lock_seconds",
    label: "临时锁定时长（秒）",
    type: "integer",
    section: "security",
    default: 900,
    options: [],
    help_text: "达到失败次数上限后，账号和来源 IP 暂停登录的时间。",
  },
  {
    key: "smtp_enabled",
    label: "启用 SMTP",
    type: "boolean",
    section: "smtp",
    default: false,
    options: [],
    help_text: "启用后可以发送测试邮件；现有业务提醒仍通过站内通知中心展示。",
  },
  {
    key: "smtp_host",
    label: "SMTP 服务端",
    type: "string",
    section: "smtp",
    default: "",
    options: [],
    help_text: "填写主机名或 IP，不要包含协议前缀。",
  },
  {
    key: "smtp_port",
    label: "SMTP 端口",
    type: "integer",
    section: "smtp",
    default: 587,
    options: [],
    help_text: "常见端口：STARTTLS 使用 587，SSL/TLS 使用 465。",
  },
  {
    key: "smtp_security_mode",
    label: "SMTP 安全模式",
    type: "enum",
    section: "smtp",
    default: "starttls",
    options: options(["none", "starttls", "ssl"]),
    help_text: "请根据邮件服务端要求选择连接安全模式。",
  },
  {
    key: "smtp_username",
    label: "SMTP 用户名",
    type: "string",
    section: "smtp",
    default: "",
    options: [],
    help_text: "需要认证时填写；密码只接受输入，不会回显。",
  },
  {
    key: "smtp_from_email",
    label: "发件人邮箱",
    type: "email",
    section: "smtp",
    default: "",
    options: [],
    help_text: "测试邮件和系统邮件使用的发件人地址。",
  },
  {
    key: "smtp_from_name",
    label: "发件人名称",
    type: "string",
    section: "smtp",
    default: "",
    options: [],
    help_text: "可选；用于邮件客户端显示的发件人名称。",
  },
  {
    key: "smtp_timeout",
    label: "SMTP 超时（秒）",
    type: "integer",
    section: "smtp",
    default: 10,
    options: [],
    help_text: "连接邮件服务端的最大等待时间。",
  },
  {
    key: "notify_maintenance",
    label: "维保到期提醒",
    type: "boolean",
    section: "notifications",
    default: true,
    options: [],
    help_text: "在站内提醒中显示已过期或即将到期的维保合同。",
  },
  {
    key: "maintenance_expiry_days",
    label: "维保到期提醒提前天数",
    type: "integer",
    section: "notifications",
    default: 30,
    options: [],
    help_text: "包含未来指定天数内到期的维保合同。",
  },
  {
    key: "notify_license_expiry",
    label: "软件许可到期提醒",
    type: "boolean",
    section: "notifications",
    default: true,
    options: [],
    help_text: "在站内提醒中显示已过期或即将到期的软件许可。",
  },
  {
    key: "license_expiry_days",
    label: "许可到期提醒提前天数",
    type: "integer",
    section: "notifications",
    default: 30,
    options: [],
    help_text: "包含未来指定天数内到期的软件许可；超额使用提醒不受此项影响。",
  },
  {
    key: "notify_open_faults",
    label: "未关闭故障提醒",
    type: "boolean",
    section: "notifications",
    default: true,
    options: [],
    help_text: "在站内提醒中显示当前仍未关闭的故障。",
  },
  {
    key: "notify_overdue_inventory",
    label: "逾期盘点提醒",
    type: "boolean",
    section: "notifications",
    default: true,
    options: [],
    help_text: "在站内提醒中显示超过结束时间且仍在进行中的盘点任务。",
  },
  {
    key: "notify_low_spare_stock",
    label: "备件低库存提醒",
    type: "boolean",
    section: "notifications",
    default: true,
    options: [],
    help_text: "在站内提醒中显示低于安全库存的备件。",
  },
  {
    key: "email_digest_enabled",
    label: "启用每日邮件摘要",
    type: "boolean",
    section: "notifications",
    default: false,
    options: [],
    help_text: "显式启用后，通过定时任务发送当前已启用的业务提醒。",
  },
  {
    key: "email_digest_people",
    label: "摘要人员",
    type: "people",
    section: "notifications",
    default: [],
    options: [],
    help_text: "从人员目录中选择最多 20 名启用且已配置邮箱的人员。",
  },
  {
    key: "email_digest_recipients",
    label: "其他收件邮箱",
    type: "emails",
    section: "notifications",
    default: [],
    options: [],
    help_text: "可填写公共邮箱等非人员地址；与摘要人员合计最多 20 个收件地址。",
  },
  {
    key: "application_url",
    label: "应用访问地址",
    type: "string",
    section: "notifications",
    default: "",
    options: [],
    help_text: "邮件中的链接使用此 HTTPS 地址。",
  },
];
